# Generated by Django 4.1.4 on 2022-12-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="zipcode",
            new_name="zipCode",
        ),
    ]
