# Generated by Django 4.1.4 on 2022-12-30 16:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("password", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("cnpj_cpf", models.CharField(max_length=18, unique=True)),
                ("responsible", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("donor", "Donnor"),
                            ("charity", "Charity"),
                            ("Not Informed", "Default"),
                        ],
                        default="Not Informed",
                        max_length=12,
                    ),
                ),
                ("isAdm", models.BooleanField(default=False)),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="addresses.address",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
