# Generated by Django 4.1.4 on 2022-12-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_cnpj_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
