services:
  db_alimento_solidario:
    container_name: db_alimento_solidario_container
    image: postgres:14.6
    env_file: .env
    ports: 
      - 5434:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $(POSTGRES_USER) -d $(POSTGRES_DB)"]
      interval: 30s
      timeout: 10s
      retries: 5
      
  migrations: 
    container_name: migrations_container
    build: .
    command: python manage.py migrate
    depends_on: 
      db_alimento_solidario:
        condition: service_healthy

  app_django:
    container_name: app_django_container
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    depends_on:
      db_alimento_solidario:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - .:/app_django

  
      