# Generated by Django 4.1.3 on 2023-01-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='expiration_date',
            new_name='expiration',
        ),
    ]
