# Generated by Django 4.1.3 on 2023-01-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_rename_expiration_date_donations_expiration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='donations',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
