# Generated by Django 4.1.3 on 2023-01-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_rename_classification_donations_classification_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='classification_id',
            new_name='classification',
        ),
    ]
