# Generated by Django 4.1.4 on 2023-01-03 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classifications", "0001_initial"),
        ("donations", "0006_alter_donations_classification_alter_donations_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donations",
            name="classification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="classifications.classification",
            ),
        ),
    ]
